export const PUBLIC_RUNTIME_CONFIG_KEYS = [
  "HERD_ARTIFACT_RELEASE_ID",
  "HERD_ATTESTATION_AUDIENCE",
  "HERD_ATTESTATION_IMAGE_DIGEST",
  "HERD_ATTESTATION_IMAGE_DIGESTS",
  "HERD_ATTESTATION_MAX_AGE_SECONDS",
  "HERD_ATTESTATION_PROJECT_ID",
  "HERD_ATTESTATION_ROOT_CERTIFICATE",
  "HERD_ATTESTATION_ROOT_FINGERPRINT",
  "HERD_ATTESTATION_SERVICE_ACCOUNT",
  "HERD_ATTESTATION_SWVERSIONS",
  "HERD_EVALUATOR_KEY_ID",
  "HERD_EVALUATOR_MEASUREMENT",
  "HERD_EVALUATOR_POLICY_SIGNING_KEY_ID",
  "HERD_EVALUATOR_POLICY_SIGNING_PUBLIC_KEY",
  "HERD_EVALUATOR_PUBLIC_KEY",
  "HERD_EVALUATOR_RESULT_SIGNING_KEY_ID",
  "HERD_EVALUATOR_RESULT_SIGNING_PUBLIC_KEY",
  "HERD_EVALUATOR_TRANSPARENCY_SIGNING_KEY_ID",
  "HERD_EVALUATOR_TRANSPARENCY_SIGNING_PUBLIC_KEY",
  "HERD_RELEASE_CONFIGURATION_SHA256",
  "HERD_RELEASE_ID",
] as const;

export type PublicRuntimeConfigKey = (typeof PUBLIC_RUNTIME_CONFIG_KEYS)[number];
export type PublicRuntimeConfig = Partial<Record<PublicRuntimeConfigKey, string>>;

declare global {
  interface Window {
    __HERD_PUBLIC_RUNTIME_CONFIG__?: PublicRuntimeConfig;
  }
}

export function publicRuntimeValue(key: PublicRuntimeConfigKey): string | undefined {
  if (typeof window !== "undefined") {
    return window.__HERD_PUBLIC_RUNTIME_CONFIG__?.[key];
  }
  return process.env[`NEXT_PUBLIC_${key}`];
}
